services:
  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # certificados Let's Encrypt (persistentes no host)
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    environment:
      - SERVER_NAME=${SERVER_NAME}
    restart: unless-stopped

  api:
    build: ./api
    environment:
      - NODE_ENV=production
      - PORT=3000
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - SNS_TOPIC_ARN=${SNS_TOPIC_ARN}
      - ALLOW_ORIGIN=https://${SERVER_NAME}
    expose:
      - "3000"
    restart: unless-stopped
