# 1) build do front (Vite)
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2) nginx para servir o build e proxy da API
FROM nginx:alpine
RUN mkdir -p /var/www/certbot
COPY infra/web/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
HEALTHCHECK CMD wget -q -O - http://localhost/ || exit 1
